# Protocol 01: Project Brief Creation - Gate Configuration
# This file defines automated validation gates for Protocol 03 (01)

protocol_id: "03"
protocol_title: "Project Brief Creation"
notes: |
  Gate automation for project brief creation workflow.
  Ensures discovery evidence verification, structural integrity, and approval compliance.

validators:
  - name: "gate_1_discovery_evidence"
    command: "python3 scripts/validate_gate_03_discovery.py"
    description: "Validates discovery artifacts and resolves inconsistencies"
    prerequisite: true
    
  - name: "gate_2_structural_integrity"
    command: "python3 scripts/validate_gate_03_structure.py"
    description: "Validates brief structure, traceability, and completeness"
    prerequisite: false
    
  - name: "gate_3_approval_compliance"
    command: "python3 scripts/validate_gate_03_approvals.py"
    description: "Validates client and internal approvals"
    prerequisite: false

artifacts:
  - path: ".artifacts/protocol-03/project-brief-validation-report.json"
    description: "Discovery artifact validation results"
    status: "pending"
    
  - path: ".artifacts/protocol-03/validation-issues.md"
    description: "Documented inconsistencies and resolutions"
    status: "pending"
    
  - path: ".artifacts/protocol-03/context-summary.md"
    description: "Client goals and success metrics summary"
    status: "pending"
    
  - path: ".artifacts/protocol-03/PROJECT-BRIEF.md"
    description: "Implementation-ready project brief"
    status: "pending"
    
  - path: ".artifacts/protocol-03/traceability-map.json"
    description: "Traceability links to source artifacts"
    status: "pending"
    
  - path: ".artifacts/protocol-03/brief-structure-report.json"
    description: "Structural validation results"
    status: "pending"
    
  - path: ".artifacts/protocol-03/BRIEF-APPROVAL-RECORD.json"
    description: "Client and internal approval evidence"
    status: "pending"

quality_thresholds:
  validation_score: 0.95
  structural_coverage: 1.0
  client_approval: true
  internal_approval: true
