#!/usr/bin/env python3
"""
Generate Protocol Checklist
Generates the PROTOCOL-CHECKLIST.md for tracking execution progress.
"""
import argparse
import json
import sys
from pathlib import Path
from datetime import datetime

def generate_checklist_markdown(sequence_data: dict, timeline_data: dict, brief_data: dict) -> str:
    """Generate the protocol checklist markdown document."""
    
    project_name = brief_data.get('project_name', 'Project')
    
    md = f"""# Protocol Execution Checklist

## Project: {project_name}

**Generated:** {datetime.now().isoformat()}

---

## Instructions

Use this checklist to track protocol execution progress. Mark items as complete using `[x]` when finished.

---

## Pre-Execution Checklist

- [ ] Project brief reviewed and approved
- [ ] Execution plan reviewed and approved
- [ ] Timeline estimates accepted
- [ ] Team resources allocated
- [ ] Environment setup complete

---

## Protocol Execution Checklist

"""
    
    sequence = sequence_data.get('sequence', [])
    phases = sequence_data.get('phases', [])
    protocol_estimates = {p['protocol_id']: p for p in timeline_data.get('timeline', {}).get('protocol_estimates', [])}
    
    for phase in phases:
        phase_num = phase.get('phase_number', 0)
        md += f"### Phase {phase_num}\n\n"
        
        for protocol in phase.get('protocols', []):
            protocol_id = protocol.get('id')
            protocol_name = protocol.get('name')
            
            estimate = protocol_estimates.get(protocol_id, {}).get('estimate', {})
            typical_hours = estimate.get('typical_hours', 'N/A')
            
            md += f"#### Protocol {protocol_id}: {protocol_name}\n\n"
            md += f"*Estimated: {typical_hours} hours*\n\n"
            
            # Standard checklist items for each protocol
            md += f"- [ ] Prerequisites verified\n"
            md += f"- [ ] Input artifacts collected\n"
            md += f"- [ ] Protocol execution started\n"
            md += f"- [ ] Quality gates passed\n"
            md += f"- [ ] Output artifacts generated\n"
            md += f"- [ ] Validation complete (score ≥ 0.95)\n"
            md += f"- [ ] Handoff to next protocol ready\n"
            md += f"\n"
            
            # Add notes section
            md += f"**Notes:**\n"
            md += f"```\n"
            md += f"Start Date: \n"
            md += f"End Date: \n"
            md += f"Actual Hours: \n"
            md += f"Blockers: \n"
            md += f"```\n\n"
        
        md += "---\n\n"
    
    # Add post-execution checklist
    md += """## Post-Execution Checklist

- [ ] All protocols completed
- [ ] All quality gates passed
- [ ] Evidence package assembled
- [ ] Final validation complete
- [ ] Handoff documentation prepared
- [ ] Stakeholder sign-off obtained

---

## Summary

| Metric | Planned | Actual |
|--------|---------|--------|
| Total Protocols | | |
| Total Hours | | |
| Start Date | | |
| End Date | | |
| Quality Score | | |

---

## Sign-Off

| Role | Name | Date | Signature |
|------|------|------|-----------|
| Executor | | | |
| Reviewer | | | |
| Approver | | | |

---

*This checklist was generated by Protocol 05b - Project Protocol Orchestration*
"""
    
    return md

def main():
    parser = argparse.ArgumentParser(description='Generate protocol execution checklist')
    parser.add_argument('--sequence', required=True, help='Path to protocol-sequence.json')
    parser.add_argument('--timeline', required=True, help='Path to timeline-estimate.json')
    parser.add_argument('--brief', required=True, help='Path to project-brief-parsed.json')
    parser.add_argument('--output', help='Output markdown file path')
    parser.add_argument('--workspace', default='.', help='Workspace root path')
    args = parser.parse_args()
    
    workspace = Path(args.workspace).resolve()
    
    print(f"[PROTOCOL 05B | PHASE 6] Generating protocol checklist...")
    
    # Load input files
    def load_json(path_arg):
        path = Path(path_arg)
        if not path.is_absolute():
            path = workspace / path
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    sequence_data = load_json(args.sequence)
    timeline_data = load_json(args.timeline)
    brief_data = load_json(args.brief)
    
    # Generate checklist
    checklist_md = generate_checklist_markdown(sequence_data, timeline_data, brief_data)
    
    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = workspace / 'PROTOCOL-CHECKLIST.md'
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(checklist_md)
    
    # Also save to artifacts
    artifacts_path = workspace / '.artifacts' / 'protocol-05b' / 'PROTOCOL-CHECKLIST.md'
    artifacts_path.parent.mkdir(parents=True, exist_ok=True)
    with open(artifacts_path, 'w', encoding='utf-8') as f:
        f.write(checklist_md)
    
    print(f"[PROTOCOL 05B | PHASE 6] Protocol checklist generated")
    print(f"  - Output: {output_path}")
    print(f"  - Artifact: {artifacts_path}")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
